on: [push]


jobs:
  my-job:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'Toby Mason-Barney'
    - name: output
      run: |
        echo ${{ steps.hello.outputs.memory }}
        echo "total memory sucessfully output"
